---
- name: Config elk with Docker
  hosts: elk
  remote_user: CsecAdmin
  become: true 
  tasks:

  - name: docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Python Docker module
    pip:
      name: docker
      state: present

  - name: Use more memory
    sysctl:
      name: vm.max_map_count
      value: '262144'
      state: present
      reload: yes


  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
  

  - name: Removing Apache2
    apt:
      name: apache2
      state: absent


  - name: download and launch a docker web container
    docker_container:
      name: sebp
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports: 80:80, 5601:5601, 9200:9200, 5044:5044

